### PR TITLE
ing english added

### PR DESCRIPTION
**Pull request by tinedel**

### CODE REVIEW

**Comment by DanielHaitink** [comment]
Hey! Thanks for adding support!

Could you add a small test file to the testfiles directory? This is useful for reference in the future

**Comment by tinedel** [comment]
Sure.

I've tried to integrate abn amro as well but it's coming out a bit
convoluted

So we'll see how it goes

**Comment by tinedel** [comment]
added a file

it's not an automated test, isn't it?
is it just a test file to be able to check if it works manually?

**Comment by DanielHaitink** [comment]
Yes indeed it is just for manual testing in the future. Since I do not know what all the different files contain, it is useful for me to have some kind of reference. (Or anyone else working on the project for that matter)

I saw your ABNAMRO branch haha, glad that someone is working on it!

**Review by DanielHaitink — APPROVED** [review]

**Pull request merged**
